
filename_database = "sqlite:////users/nassi/PycharmProjects/confluence-task-reporting/prod.db"

# Full path to where the logfiles shall be stored or empty
log_dir = "/users/nassi/PycharmProjects/confluence-task-reporting/logs/"

# Duration in Seconds between each call to Confluence
sleep_between_crawl_tasks = 1.5

# Name of the logger:
logger_name = "CONFTASK"