
# filename_database = "sqlite:///prod.db?check_same_thread=False"
filename_database = "sqlite:///prod.db?check_same_thread=False"

# Full path to where the logfiles shall be stored or empty
log_dir = "logs/"

# Duration in Seconds between each call to Confluence
sleep_between_crawl_tasks = 0.5

# Name of the logger:
logger_name = "CONFTASK"